Added credit eligibility.
openedx-unsupported/edx-analytics-exporter pull request #21
Opened 2017-06-20 19:28 UTC by dsjen

[EDUCATOR-154](https://openedx.atlassian.net/browse/EDUCATOR-154)

This adds `credit_crediteligibility` to the research data package (or so I hope).  I've documented the fields at https://openedx.atlassian.net/wiki/display/EDUCATOR/Credit+Eligibility.

I don't think there's really way to test this other than running the query on the read replica, which I did.  If there is another way to confirm that this works, please let me know!

@edx/analytics @efischer19

2017-06-20 19:47 UTC, efischer19 approved these changes
👍 LGTM!

2017-06-20 20:43 UTC, thallada approved these changes
This looks good to me too, but I'm not familiar with this repo.

2017-06-20 20:43 UTC, iloveagent57 requested changes
Well, you definitely have to fix that syntax error :)

2017-06-20 20:43 UTC, iloveagent57 commented on exporter/tasks.py
> +           cc.course_key,
You have to remove the comma after this last column.

2017-06-20 20:43 UTC, iloveagent57 commented on exporter/tasks.py
> +    ORDER BY cc.username
You should order by `ce.username`.

2017-06-21 13:06 UTC, dsjen commented
@iloveagent57 -- updated!  Please re-review!

2017-06-21 15:53 UTC, brianhw commented
You can also test this by running a test export on admin.edx.org.  Pick an
org with fewer and smaller courses, not MITx.   Make sure you specify a
test output directory, so that it's not published with the regular exports.
  Look at any mid-week test that Olga runs when testing Data Czar changes
for an example.

But before you do that, you should add the task to the list of tasks to be
performed, or it will never be run.

On Wed, Jun 21, 2017 at 9:06 AM, Dennis Jen <notifications@github.com>
wrote:

> @iloveagent57 <https://github.com/iloveagent57> -- updated! Please
> re-review!
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/edx-analytics-exporter/pull/21#issuecomment-310072391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACaqz9nbCJB_m-51QSM33QujBr0VXz3nks5sGRVegaJpZM4OAC5P>
> .
>

2017-06-21 20:20 UTC, dsjen commented on exporter/tasks.py
> +           cc.course_key
It turns out that the other columns used `course_id` rather than `course_key`.  Would this be better as `course_id`?  Leaving is as `course_key` would be consistent with the original table, but updating to `course_id` would be more consistent with the other exports.  Is there a preferred export format?  @brianhw especially :)

2017-06-21 20:28 UTC, iloveagent57 commented on exporter/tasks.py
> +           cc.course_key
The people consuming the exports don't really care about the original table, so I would say alias the `course_key` column to `course_id` to make it consistent with the rest of the package.

2017-06-21 20:33 UTC, dsjen commented on exporter/tasks.py
> +           cc.course_key
Yeah, I was thinking the same thing too.  Ok, done!

2017-06-23 14:21 UTC, dsjen commented
No courses were found using the `analytics-exporter-master-test` job when I tried testing on both my branch and on master with a few different organizations. However, it appears that tables were created with the `analytics-exporter-master` job, but it fails at the end with `AccessDenied` upload errors at the end of the slave job: http://admin.edx.org:8080/job/analytics-exporter-slave/11630/console

2017-06-23 18:06 UTC, dsjen commented
@iloveagent57 -- hey! After updating the bucket, the errors went away, http://admin.edx.org:8080/job/analytics-exporter-slave/11631/console. Concerns? Ok to merge?

2017-06-26 15:24 UTC, iloveagent57 approved these changes

2017-06-26 15:25 UTC, merged

2017-06-26 15:26 UTC, dsjen commented
@iloveagent57 -- thanks!  I'll cherry pick the commit onto the release branch and tag you.