handle course keys with non ascii characters
openedx-unsupported/edx-analytics-exporter pull request #41
Opened 2019-11-19 21:22 UTC by estute

2019-11-19 21:41 UTC, macdiesel approved these changes

2019-11-19 21:51 UTC, bmedx approved these changes
As long as everything uses `entity_name` for finding the files this looks 👍 to me

2019-11-19 22:29 UTC, brianhw requested changes
Looks like there is a definition of get_filename() in ForumsTask that references get_course_name() directly.   It could probably be fixed by having it reference entity_name instead.

2019-11-21 17:22 UTC, pwnage101 commented on exporter/tasks.py
> +    return ''.join(substituted_string)
Seems like this is double-joined?  i.e. substituted_string is already a string, so `''.join(substituted_string) is a no-op?

2019-11-21 17:32 UTC, pwnage101 commented on exporter/tasks.py
> +    return ''.join(substituted_string)
Also, just checking that you need underscores because you could do this instead but it would use question marks as the replacement: `six.text_type(string).encode('ascii', 'replace')`

2019-12-02 18:37 UTC, estute commented on exporter/tasks.py
> +    return ''.join(substituted_string)
Yeah, that was accidentally left in. As for the "?" vs "_" issue, I prefer the latter in filenames.

2019-12-02 18:46 UTC, estute commented
These fixes will only get us part of the way. The exporter jobs will still fail due in the LMS, but this will at least get us to that part.

2019-12-02 19:52 UTC, pwnage101 approved these changes

2019-12-02 20:02 UTC, merged